#Playlist
playlist=TODO.txt (joue la playlist indiqué dans /playlist)
random=true

#Wifi & Bluetooth
wifi_enabled=1 (0=Desactive le wifi, 1=Active le wifi. Laissez sur 1)
wifi_ssid=monwifi (nom de votre reseau wifi)
wifi_password=monpasse (mot de passe de votre reseau wifi)
bluetooth_enabled=0 (0=Desactive le bluetooth, 1=Active le bluetooth. Laissez sur 0. Cela depends si vous avez des interferences, par exemple manette 8Bitdo Pro 3)
bluetooth_name=ESP32-GIF (Nom Bluetooth)

wifi_static_enabled=1 (0=DHCP, 1=IP fixe. Preferez une IP fixe.)
wifi_static_ip=192.168.20.240 (À renseigner seulement si wifi_static_enabled=1)
wifi_gateway=192.168.20.1  (À renseigner seulement si wifi_static_enabled=1)
wifi_subnet=255.255.255.0  (À renseigner seulement si wifi_static_enabled=1)
wifi_dns1=1.1.1.1  (À renseigner seulement si wifi_static_enabled=1)
wifi_dns2=8.8.8.8  (À renseigner seulement si wifi_static_enabled=1)

#MQQT
recalbox_ip=192.168.20.104 (Adresse IP fixe de votre Recalbox)
